import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
const baseProduct={id:'test-product',productName:'Test product',sku:'TEST',platforms:['Amazon'],productInformation:'Test dimensions and material',imageCount:9,imageFormatsAndSizes:'Square'};
const payload=()=>({submissionKey:crypto.randomUUID(),contactName:'Test Person',email:'test@example.com',country:'Lithuania',rushRequested:false,consent:true,website:'',products:[{...baseProduct}]});
async function setup(t,rateLimit=100){const dir=await mkdtemp(path.join(os.tmpdir(),'nonobject-test-'));const app=await createApp({dataDir:dir,live:false,rateLimit});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});return{dir,url:`http://127.0.0.1:${server.address().port}`};}
const png=await sharp({create:{width:10,height:10,channels:3,background:'#ff5a1f'}}).png().toBuffer();
function data(value,files=true,bytes=png){const form=new FormData();form.append('payload',JSON.stringify(value));if(files)for(const p of value.products)form.append(`files-${p.id}`,new Blob([bytes],{type:'image/png'}),'photo.png');return form;}
test('persists independent SKU photos and returns same request on retry',async t=>{const{dir,url}=await setup(t);const value=payload();value.products.push({...baseProduct,id:'product-2',sku:'../../test-two'});const response=await fetch(url+'/api/enquiries',{method:'POST',body:data(value)});assert.equal(response.status,201);const result=await response.json();assert.equal(result.preview,true);assert.equal(result.confirmationSent,false);const retry=await(await fetch(url+'/api/enquiries',{method:'POST',body:data(value)})).json();assert.equal(retry.requestId,result.requestId);assert.equal(retry.duplicate,true);const dirs=await readdir(path.join(dir,'enquiries'));assert.equal(dirs.length,1);const record=JSON.parse(await readFile(path.join(dir,'enquiries',dirs[0],'enquiry.json'),'utf8'));assert.equal(record.products.length,2);assert.equal(record.estimate.total,130);assert.notEqual(record.products[0].files[0].storageKey,record.products[1].files[0].storageKey);assert.equal(record.products[1].files[0].storageKey.includes('../'),false);assert.deepEqual(record.notifications,{});assert.equal((await readdir(path.join(dir,'pending'))).length,0);});
test('server rejects missing uploads, invalid content and quantities',async t=>{const{url}=await setup(t);for(const body of [data(payload(),false),data(payload(),true,Buffer.from('<script>alert(1)</script>')),data({...payload(),products:[{...baseProduct,imageCount:2}]})]){const r=await fetch(url+'/api/enquiries',{method:'POST',body});assert.equal(r.status,400);}});
test('cross-origin requests rejected and request rate is bounded',async t=>{const{url}=await setup(t,1);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',headers:{Origin:'https://evil.example'},body:data(payload())})).status,403);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',body:data(payload())})).status,201);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',body:data(payload())})).status,429);});
