import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
const payload=()=>({submissionKey:crypto.randomUUID(),contactName:'Test Person',email:'test@example.com',projectNeed:'Complete listing visuals',productCount:'100+',platforms:['Amazon','Allegro'],materialsStatus:'Not sure yet',timeline:'Flexible',consent:true,website:''});
async function setup(t,rateLimit=100){const dir=await mkdtemp(path.join(os.tmpdir(),'nonobject-test-'));const app=await createApp({dataDir:dir,live:false,rateLimit});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});return{dir,url:`http://127.0.0.1:${server.address().port}`};}
const png=await sharp({create:{width:10,height:10,channels:3,background:'#ff5a1f'}}).png().toBuffer();
function data(value,file){const form=new FormData();form.append('payload',JSON.stringify(value));if(file)form.append(file.field||'attachments',new Blob([file.bytes],{type:file.type}),file.name);return form;}
test('100+ product brief needs no per-product entries or files and retries safely',async t=>{const{dir,url}=await setup(t);const value=payload();const response=await fetch(url+'/api/enquiries',{method:'POST',body:data(value)});assert.equal(response.status,201);const result=await response.json();assert.equal(result.preview,true);assert.equal(result.confirmationSent,false);const retry=await(await fetch(url+'/api/enquiries',{method:'POST',body:data(value)})).json();assert.equal(retry.requestId,result.requestId);assert.equal(retry.duplicate,true);const dirs=await readdir(path.join(dir,'enquiries'));assert.equal(dirs.length,1);const record=JSON.parse(await readFile(path.join(dir,'enquiries',dirs[0],'enquiry.json'),'utf8'));assert.equal(record.productCount,'100+');assert.deepEqual(record.attachments,[]);assert.equal('products' in record,false);assert.deepEqual(record.notifications,{});assert.equal((await readdir(path.join(dir,'pending'))).length,0);});
test('optional image attachment is saved privately and file signatures are checked',async t=>{const{dir,url}=await setup(t);const value=payload();let response=await fetch(url+'/api/enquiries',{method:'POST',body:data(value,{bytes:png,type:'image/png',name:'../product.png'})});assert.equal(response.status,201);const dirs=await readdir(path.join(dir,'enquiries'));const record=JSON.parse(await readFile(path.join(dir,'enquiries',dirs[0],'enquiry.json'),'utf8'));assert.equal(record.attachments.length,1);assert.match(record.attachments[0].storageKey,/^Attachments\//);assert.equal(record.attachments[0].storageKey.includes('../'),false);response=await fetch(url+'/api/enquiries',{method:'POST',body:data(payload(),{bytes:Buffer.from('<script>alert(1)</script>'),type:'image/png',name:'bad.png'})});assert.equal(response.status,400);response=await fetch(url+'/api/enquiries',{method:'POST',body:data(payload(),{bytes:png,type:'image/png',name:'wrong.png',field:'files-sku'})});assert.equal(response.status,400);});
test('cross-origin requests rejected and request rate is bounded',async t=>{const{url}=await setup(t,1);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',headers:{Origin:'https://evil.example'},body:data(payload())})).status,403);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',body:data(payload())})).status,201);assert.equal((await fetch(url+'/api/enquiries',{method:'POST',body:data(payload())})).status,429);});
