import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculateEstimate} from '../src/domain/pricing.js';
import {enquirySchema,imageType,attachmentType} from '../src/domain/validation.js';
const enquiry={submissionKey:crypto.randomUUID(),contactName:'Test',email:'test@example.com',projectNeed:'Complete listing visuals',productCount:'100+',platforms:['Amazon'],materialsStatus:'Not sure yet',timeline:'Flexible',consent:true,website:''};
test('exactly 9 images uses the approved €65 package',()=>assert.equal(calculateEstimate([{imageCount:9}]).total,65));
test('other approved quantities use €10 each',()=>{assert.equal(calculateEstimate([{imageCount:3}]).total,30);assert.equal(calculateEstimate([{imageCount:8}]).total,80);});
test('sums SKUs without rounding three packages to the order minimum',()=>{const e=calculateEstimate([{imageCount:9},{imageCount:9},{imageCount:9}]);assert.equal(e.total,195);assert.equal(e.belowMinimum,true);});
test('rush adds exactly 30%, while order-minimum check remains on image scope',()=>{const e=calculateEstimate([{imageCount:9},{imageCount:9},{imageCount:9}],true);assert.equal(e.total,253.5);assert.equal(e.rushAmount,58.5);assert.equal(e.belowMinimum,true);});
test('10+ images explicitly require a manual quote',()=>{const e=calculateEstimate([{imageCount:10},{imageCount:9}],true);assert.equal(e.total,null);assert.equal(e.manual,true);assert.equal(e.knownSubtotal,65);});
test('blocks invalid quantities',()=>{for(const imageCount of [0,2,-1,3.5,101,NaN])assert.throws(()=>calculateEstimate([{imageCount}]));});
test('valid 100+ product brief accepts optional fields without per-product detail',()=>{const p=enquirySchema.parse(enquiry);assert.equal(p.companyName,'');assert.equal(p.projectUrl,'');assert.equal(p.productCount,'100+');});
test('brief rejects missing contact, choices, consent and unsafe links',()=>{for(const change of [{email:'bad'},{contactName:''},{consent:false},{website:'spam'},{projectNeed:''},{productCount:'101'},{platforms:[]},{materialsStatus:''},{timeline:''},{projectUrl:'javascript:alert(1)'},{materialsLink:'ftp://example.com'}])assert.equal(enquirySchema.safeParse({...enquiry,...change}).success,false);});
test('signature rejects files disguised as images and PDFs',()=>{assert.equal(imageType(Buffer.from('<script>alert(1)</script>')),null);assert.equal(imageType(Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0])),'image/png');assert.equal(attachmentType(Buffer.from('%PDF-1.7 test')),'application/pdf');});
